services:
  oshi-api:
    image: killbasa/oshi-api:latest
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./data:/etc/oshi-api/data
